import type { Metadata } from "next";
import { Creepster, Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Provider } from "@/components/ui/provider";

const creepster = Creepster({
  variable: "--font-creepster",
  subsets: ['latin'],
  weight: ["400"]
})

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ['latin'],
  weight: ['400', '700'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en" className={`${poppins.variable} ${creepster.variable} `}>
      <body
        className="antialiased bg-background_body"
        >
        <Provider >
        <Navbar/>
        {children}
    </Provider>
      </body>
    </html>
  );
}
